### ISSUE TITLE
Doesn't work in Cron

### ISSUE THREAD

**Issue by Phlomos** [SPDUK/youtube-subscription-dl#10] opened 2019-12-06 15:49 UTC
I have it up and running as a normal user, started from the command line. No issues. I can enter it into Crontab and start the crontab with Webmin. It also works (after entering the access code).
But in Cron there's no way:
Already the line
export XDG_RUNTIME_DIR=/run/user/$(id -u)
is of no use, because this file only exists, during the user is logged in. But Cron runs, even if nobody is logged in, apart that I run the command as the user plex, which isn't even allowed to log in.
I see, that the Cron calls the script "yt-subs.sh", but runs so quickly, that I don't think, "youtube-dl" ever gets called.
I changed permissions and I also changed the user, under which the script is started from Cron (plex, root, ordinary_user). It didn't even matter, if the user is logged in or not.
Unfortunately, debugging JavaScript, called from Cron is over my competence.
Again, from the command line and from WebMin, all runs flawlessly.
(This is on a Debian with all the latest updates and upgrades installed.)

**Comment by SPDUK** [comment] 2019-12-11 09:42
It should work from inside cron as that's how I have used it. (I know works on my machine isn't a great response 😂)

Does it work inside cron as the default user?

If you have `libnotify-bin` installed it will display any error that occurs as a notification (displays when running inside cron too), so that should help if the error is something obvious like when a config file is missing, which sounds like what the issue is.

Since the script is being called the only thing I can think of it that it's throwing an error because the config files are set up incorrectly, so potentially the `plex` user doesn't have the same setup as your `default_user`, as the files are stored in the folder where you download them (as the default user) and you're calling them from the `plex` user, inside `default_user`'s directory?

**Comment by Phlomos** [comment] 2019-12-11 16:03
Hello,Thanks for your reply!Am 11.12.2019 um 10:42 schrieb Steve P <notifications@github.com>:Does it work inside cron as the default user?I don’t know, what the default user is, but I tried as “root”, “plex” and myself “moetteli”. Non works inside Cron.If you have libnotify-bin installed it will display any error that occurs as a notification (displays when running inside cron too), Does this also work on a headless (and GUI-less) server? Because this is a a headless Debian Plex server.so that should help if the error is something obvious like when a config file is missing, which sounds like what the issue is.Strange, that I can run the very same command without issue on the command line as root, plex and moetteli. I can also start the cron entry in WebMin - again, it doesn’t matter what user. I had though to enter on every “plateform” (command line and WebMin), the first time this allowance code, that one has to get from the given Google URL.As an example plex:$ whoamiplex$ crontab -l* * * * * /usr/local/src/youtube-subscription-dl/yt-subs.sh(As you can see, it runs every minute at the moment (as the user plex) for debugging purposes.)Since the script is being called the only thing I can think of it that it's throwing an error because the config files are set up incorrectly,Why then not, when I run it from the command line or from WebMin?Anyway, here’s the configuration file:  It’s in /etc:# ls -alh /etc/youtube-dl.conf -rw-r--r-- 1 plex root 461 Nov 22 11:59 /etc/youtube-dl.confso potentially the plex user doesn't have the same setup as your default_userI don’t know, what a default user is. I never use any other than root and I only log in remotely. No GUI is installed.Supposedly ‘moetteli’ would be the default user: Even if I start it from Cron as the user moetteli, it doesn’t work. But from the command line, it does.as the files are stored in the folder where you download them (as the default user) and you're calling them from the plex user, inside default_user's directory?I tried with the root, plex and moetteli user - from the command line and in cron. Meaning cron runned the script as user root, plex and moetteli and it never worked. But started from WebMin or command line as these very same users, they all worked.In your script, I see, that you set the working directory:DIR="$(cd "$(dirname "$0")" && pwd)"I see, that it enters the script, because I pot a “logger” command in it as you can see here: Of course, no error message in syslog or messages. No output, even if I redirect in cron all output into a file.Thanks for your help!Philip

**Comment by Phlomos** [comment] 2019-12-11 16:03
Hello,


Thanks for your reply!


> Am 11.12.2019 um 10:42 schrieb Steve P <notifications@github.com <mailto:notifications@github.com>>:
> 
> Does it work inside cron as the default user?

I don’t know, what the default user is, but I tried as “root”, “plex” and myself “moetteli”. Non works inside Cron.


> If you have libnotify-bin installed it will display any error that occurs as a notification (displays when running inside cron too), 

Does this also work on a headless (and GUI-less) server? Because this is a a headless Debian Plex server.


> so that should help if the error is something obvious like when a config file is missing, which sounds like what the issue is.

Strange, that I can run the very same command without issue on the command line as root, plex and moetteli. I can also start the cron entry in WebMin - again, it doesn’t matter what user. I had though to enter on every “plateform” (command line and WebMin), the first time this allowance code, that one has to get from the given Google URL.
As an example plex:

$ whoami
plex
$ crontab -l
* * * * * /usr/local/src/youtube-subscription-dl/yt-subs.sh

(As you can see, it runs every minute at the moment (as the user plex) for debugging purposes.)


> Since the script is being called the only thing I can think of it that it's throwing an error because the config files are set up incorrectly,

Why then not, when I run it from the command line or from WebMin?
Anyway, here’s the configuration file:

 It’s in /etc:

# ls -alh /etc/youtube-dl.conf 
-rw-r--r-- 1 plex root 461 Nov 22 11:59 /etc/youtube-dl.conf


> so potentially the plex user doesn't have the same setup as your default_user

I don’t know, what a default user is. I never use any other than root and I only log in remotely. No GUI is installed.
Supposedly ‘moetteli’ would be the default user: Even if I start it from Cron as the user moetteli, it doesn’t work. But from the command line, it does.


> as the files are stored in the folder where you download them (as the default user) and you're calling them from the plex user, inside default_user's directory?

I tried with the root, plex and moetteli user - from the command line and in cron. Meaning cron runned the script as user root, plex and moetteli and it never worked. But started from WebMin or command line as these very same users, they all worked.
In your script, I see, that you set the working directory:

DIR="$(cd "$(dirname "$0")" && pwd)"

I see, that it enters the script, because I pot a “logger” command in it as you can see here: 

Of course, no error message in syslog or messages. No output, even if I redirect in cron all output into a file.


Thanks for your help!
Philip

**Comment by SPDUK** [comment] 2019-12-15 19:51
I have no real clue what the problem is, but there's a post on medium which uses plex and this repo together and it seemingly works for them. Maybe giving that a read will help?

https://medium.com/@mightywomble/using-plex-to-deliver-your-youtube-subscription-videos-db219ad95dd6

**Comment by SPDUK** [comment] 2020-01-10 21:16
Gonna close this as I assume it's just a config issue

**Closed as completed** 2020-01-10 21:16 UTC
Labels: bug
